CXX = g++
CXXFLAGS = -std=c++0x
CXXFLAGS = -Wall
CXXFLAGS = -pedantic-errors
CXXFLAGS = -g

SRC1 = dlist.cpp main.cpp supplied.o 
HEADER =  dlist.h

finalProject: ${SRC1}  ${Header}
	${CXX} ${CXXFLAGS}  ${SRC1}  -o main 

clean:
	 rm -f main
