CXX = g++
CXXFLAGS = -std=c++0x
CXXFLAGS = -Wall


SRC1 = data.cpp arrayqueue.cpp myUtil.cpp arraystack.cpp main.cpp 

HEADER =  data.h arrayqueue.h arraystack.h myutil.h

finalProject: ${SRC1}  ${Header}
	${CXX} ${CXXFLAGS}  ${SRC1}  -o proj2 

clean:
	 rm -f proj2
