CXX = g++
CXXFLAGS = -std=c++0x
CXXFLAGS = -Wall


SRC1 = winery.cpp db.cpp myUtil.cpp main.cpp 

HEADER =  winery.h db.h myutil.h

finalProject: ${SRC1}  ${Header}
	${CXX} ${CXXFLAGS}  ${SRC1}  -o proj1 

clean:
	 rm -f proj1
