CXX = g++
CXXFLAGS = -std=c++0x
CXXFLAGS = -Wall


SRC1 = hashtable.cpp data.cpp myUtil.cpp main.cpp 

HEADER =  data.h hashtable.h myutil.h

finalProject: ${SRC1}  ${Header}
	${CXX} ${CXXFLAGS}  ${SRC1}  -o main

clean:
	 rm -f main
